### ISSUE TITLE
is 'jade' missing as a dep in package.json?

### ISSUE THREAD

**Issue by bixu** [secretfader/manta-cors-express#1]
```
git clone <repo>
cd <repo>
npm package install
node index.js
```

then curling `localhost:3000` i get:

```
500 Error: Cannot find module 'jade'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at new View (/Users/irvin/workspace/manta-cors-express/node_modules/express/lib/view.js:43:49)
at Function.app.render (/Users/irvin/workspace/manta-cors-express/node_modules/express/lib/application.js:486:12)
at ServerResponse.res.render (/Users/irvin/workspace/manta-cors-express/node_modules/express/lib/response.js:798:7)
at app.post._options.expires (/Users/irvin/workspace/manta-cors-express/index.js:55:7)
at callbacks (/Users/irvin/workspace/manta-cors-express/node_modules/express/lib/router/index.js:164:37)
at param (/Users/irvin/workspace/manta-cors-express/node_modules/express/lib/router/index.js:138:11)
```

(i may be doing it wrong)

**Comment by secretfader** [comment]
@bixu You caught my mistake! Jade must have already been installed on my machine globally, so I didn't catch the glitch. I just updated the repo, and added Jade, which should solve any issues.

**Comment by bixu** [comment]
Testing now - looks good.  I'm uploading a 500+mb file - is that large enough to make for a good test case?

**Comment by secretfader** [comment]
That's bigger than the ones I tested, but I don't see a reason why it
wouldn't work.

The only thing you should be aware of is Manta doesn't seem to like
uploading files with spaces in their name. I could easily fix this in the
demo app, but I don't want to make the demo app too specific... because
it's just that: a demo.
